Basic:
  API:
  # 这里是阿里云的配置,用于掉线发送邮件的,（需要域名）
    AliYuncs:
      accessKeyId: xxxxx
      accessKeySecret: xxxxx
    Server: xxxxx
  #下面为腾讯云的配置 （暂未用到）
    Tencent:
      Cos:
        bucket: xxxxx
        region: xxxxx
      secretId: xxxxx
      secretKey: xxxxx
  BotName: xxxxx
  CoinName: xxxxx
  # 基本事件
  Event:
    JoinGroup: true
    KickGroup: true
    LeaveGroup: true
    Mute: true
    NewFriend: true
    PermissionChange: true
  # mirai-api-http配置
  MAH:
    BotQQ: xxxxx
    MiraiAuthKey: xxxxx
    MiraiHost: http://localhost:8080
  Permission:
    Admin:
    - xxxxx
    Master: xxxxx
    MasterName: xxxx
    DebugGroup: xxxxx
    Debug: false
    Rest: false               # 是否开启睡眠休息模式
    DefaultAcceptInvite: true # 是否默认接受邀请
Saya:
  AiWaifu:
    Disabled: false
  AiWrite:
    Disabled: false
  AiWriter:
    Disabled: false
  DrawSomething:
    Disabled: false
  DriftingBottle:
    Disabled: false
  EnglishTest:
    Disabled: false
  FutureLetter:
    Disabled: false
  GroupConfig:
    Disabled: false
  GroupSend:
    Disabled: false
  Luck:
    Disabled: false
  MapMaker:
    Disabled: false
  ModSearch:
    Disabled: false
  Sign:
    Disabled: false
  StorySend:
    Disabled: false
  UserFunction:
    Disabled: false
  WordCloud:
    Disabled: false
  Yinglish:
    Disabled: false
  luck:
    Disabled: false
Final: false