Basic:
  API:
    Tencent:
      Cos:
        bucket: xxxxx
        region: xxxxx
      secretId: xxxxx
      secretKey: xxxxx
  BotName: 千音
  CoinName: 乌帕
  Event:
    DefaultAcceptInvite: true
    JoinGroup: true
    KickGroup: true
    LeaveGroup: true
    Mute: true
    NewFriend: true
    PermissionChange: true
  MAH:
    BotQQ: 959686587
    MiraiAuthKey: QJU1787569211
    MiraiHost: http://localhost:1235
  Permission:
    Admin:
    - 1787569211
    - 2225664821
    Debug: false
    DebugGroup: 871115054
    Master: 1787569211
    MasterName: xxxx
    Rest: false
Final: true
Saya:
  AiWaifu:
    Disabled: false
  ChatMS:
    Disabled: true
  DrawSomething:
    Disabled: false
  DriftingBottle:
    Disabled: true
  GroupSend:
    Disabled: false
  Luck:
    Disabled: false
  MapMaker:
    Disabled: false
  ModSearch:
    Disabled: false
  StorySend:
    Disabled: false
  WordCloud:
    Disabled: false
  Yinglish:
    Disabled: false
